dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.5.3
services:
  - postgresql
addons:
  postgresql: "10"
before_script:
  - psql -c 'create database wiki_test;' -U postgres
  - bin/rails db:test:prepare
